config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]

  resources :nekos do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'nekos#index'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :neko
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :neko
  belongs_to :user

  validates_uniqueness_of :neko_id, scope: :user_id

end

app/models/neko.rb
class Neko < ApplicationRecord
    belongs_to :user 
    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    

  has_many :nekos, dependent: :destroy 
  has_many :likes, dependent: :destroy
  has_many :liked_nekos, through: :likes, source: :neko
  has_many :comments, dependent: :destroy

  def already_liked?(neko)
    self.likes.exists?(neko_id: neko.id)
  end

  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base         
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    neko = Neko.find(params[:neko_id])
    comment = neko.comments.build(comment_params) 
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) 
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) 
    end
end

private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(neko_id: params[:neko_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(neko_id: params[:neko_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/nekos_controller.rb
class NekosController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def new
        @neko = Neko.new
      
    end
    def index
      if params[:search] == nil
        @nekos= Neko.all
      elsif params[:search] == ''
        @nekos= Neko.all
      else
        @nekos = Neko.where("town LIKE ? or way LIKE ? or thing LIKE ?",'%' + params[:search] + '%' ,'%' + params[:search] + '%' ,'%' + params[:search] + '%')
      end
    end
    
    def create
        neko = Neko.new(neko_params)
        neko.user_id = current_user.id
        if neko.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
      @neko = Neko.find(params[:id])
      @comments = @neko.comments
      @comment = Comment.new
    end
    
    def edit
      @neko = Neko.find(params[:id])
    end

    def update
      neko = Neko.find(params[:id])
      if neko.update(neko_params)
        redirect_to :action => "show", :id => neko.id
      else
        redirect_to :action => "new"
      end
    end

    def destroy
      neko = Neko.find(params[:id])
      neko.destroy
      redirect_to action: :index
    end

    private
    def neko_params
        params.require(:neko).permit(:town, :way, :thing, :cost, :image)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
  @user = User.find(params[:id]) 
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/nekos_helper.rb
module NekosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetcatschiba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1dc08dc432.js" crossorigin="anonymous"  crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <header>
  <h1>求む!保護猫を飼うためのイロハ</h1>
 </header>
 <main>
  <%= yield %>
 </main>
  </body>
</html>

app/views/nekos/edit.html.erb
<%= form_for @neko do |f| %>
    <div class="field">
    <%= f.label :住所（都道府県） %>
    <%= f.text_field :thing, :size => 140 %>
    </div>

    <div class="field">
    <%= f.label :保護猫と出会った場所（船橋市保健所等） %>
    <%= f.text_field :way, :size => 140 %>
    </div>

    <div class="field">
    <%= f.label :飼うために購入した物品 %>
    <%= f.text_field :thing, :size => 140 %>
    </div>

    <div class="field">
    <%= f.label :飼うためにかかった費用の総額 %>
    <%= f.text_field :cost, :size => 140 %>
    </div> 

    <div class="field">
    <%= f.label :備考欄 %>
    <%= f.text_field :detail, :size => 140 %>
    </div>

    <div class="field">
    <%= f.label :猫の画像等 %>
    <%= f.file_field :image %>
  </div>

    <%= f.submit "編集する" %>
  <% end %>

app/views/nekos/index.html.erb
<h3>投稿一覧</h3>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"nekos",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<%= link_to "新規投稿する", new_neko_path %>
<div class="nekos-container">

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

  <% @nekos.each do |t| %>
    <div class="neko">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.town %>
      
      

      <%= link_to "詳細へ", neko_path(t.id) %> 

      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to neko_like_path(id: t.id, neko_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
              <p>いいねを取り消す</p>
          <% end %>
      <% else %>
          <%= button_to neko_likes_path(id: t.id, neko_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
              <p>いいね</p>
          <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

      <% if user_signed_in? && current_user.id == t.user_id %>
        <%= link_to "編集する", edit_neko_path(t.id) %>
        <%= button_to "削除する", neko_path(t.id), method: :delete %>
      <% end %> 
    </div>

   
  <% end %>
  <% if user_signed_in? %>
    <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "新規登録", new_user_registration_path %></li>
    <li><%= link_to "ログイン", new_user_session_path %></li>
  <% end %>
</div>

app/views/nekos/new.html.erb
<h3>新規投稿ページ</h3>
<%= form_for @neko do |f| %>


  <div class="field">
    <%= f.label :住所（都道府県） %>
    <%= f.text_field :town, :size => 30 %>
  </div>


  <div class="field">
    <%= f.label :保護猫と出会った場所（船橋市保健所等）  %>
    <%= f.text_area :way, :size => "30x2" %>
  </div>


  <div class="field">
    <%= f.label :飼うために購入した物品  %>
    <%= f.text_area :thing, :size => "30x2" %>
  </div>


  <div class="field">
    <%= f.label :飼うまでにかかった費用の総額  %>
    <%= f.number_field :cost, :size => 10 %>
  </div>

  <div class="field">
    <%= f.label :備考等  %>
    <%= f.text_area :detail, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :猫の画像等 %>
    <%= f.file_field :image %>
  </div>
  



  <%= f.submit "新規投稿する" %>
<% end %>

<%= link_to "投稿一覧に戻る", nekos_path %>

app/views/nekos/show.html.erb
<h1>meetcatschiba</h1>
<h3>投稿詳細</h3>
<div class="neko">
  <p><%= @neko.user.email %></p>
  <p><%= @neko.town %></p>
  <p><%= @neko.way %></p>
  <p><%= @neko.thing %></p>
  <p><%= @neko.cost %></p>
  <p><%= @neko.detail %></p>
  <p><%= @neko.created_at %></p>

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@neko) %>
        <%= button_to neko_like_path(@neko), method: :delete do %>
          <i class="fas fa-heart"></i><%= @neko.likes.count %>
          <p>いいねを取り消す</p><%= @neko.likes.count %>
        <% end %>
      <% else %>
        <%= button_to neko_likes_path(@neko), method: :post do %>
          <i class="far fa-heart"></i><%= @neko.likes.count %>
          <p>いいね</p><%= @neko.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @neko.likes.count %>
      <p>いいねの数 = </p><%= @neko.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_neko_path(@neko.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @neko.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

</div>
<%= link_to "編集する", edit_neko_path(@neko.id) %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@neko, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "投稿一覧に戻る", nekos_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー名</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.nekos.each do |t| %>
  <%= t.user.name %>
<% end %>


<%= link_to "Neko一覧に戻る", nekos_path %>